### ISSUE TITLE
Blue Screen Of Death on Windows Dual Boot with the latest EFI

### ISSUE THREAD

**Issue by bunnybavros** [devboloji/Infinix-Hackintosh-Opencore-Guide#30] opened 2023-01-20 15:58 UTC
I know that getting a blue screen of death (BSOD) is a common problem when using a hackintosh, 
BUT it is so weird that **I am not getting any errors, problems, or BSODs** when using **Devboloji's 0.8.5 OpenCore.**

Anyone also facing with this problem?
**Error Code From Windows:** ACPI BIOS ERROR
**Device:** Infinix INBook X1 Pro (Intel Core i7-1065G7)

**Comment by devboloji** [comment] 2023-01-20 16:14
@bunnybavros Which Version of EFI you mean here brother?

**Comment by bunnybavros** [comment] 2023-01-20 17:35
I apologize for not providing more information and causing confusion, haha.

Previously, **I was able to dual boot between a Hackintosh and Windows using Opencore 0.8.5 EFI** 
(found here: https://github.com/devboloji/Infinix-Hackintosh-Opencore-Guide/releases/tag/OC-0.8.5-EFI-infinix-inbook-series). 
Everything was working as expected and **I saw no issues with my dual boot setup.**

However, after reinstalling my Hackintosh and upgrading to Ventura, **I began using Opencore 0.8.7 EFI** (found here: https://github.com/devboloji/Infinix-Hackintosh-Opencore-Guide/releases/tag/vfinal) **and started experiencing blue screens of death (BSOD) when trying to boot into Windows via the Opencore EFI.**

I had no idea why this was happening, so I attempted to troubleshoot by making changes to my BIOS settings, but nothing seemed to work. **I then remembered my previous setup and how I used to dual boot.**

**I decided to try using my old EFI file (Opencore 0.8.5) again, and it worked perfectly.** 
**This led me to realize that the new EFI does not support dual booting, which was causing the BSOD.**

**Comment by devboloji** [comment] 2023-01-20 17:44
@bunnybavros Do one thing brother, Take windows folder from your old 0.8.5 EFI, and paste it on to your latest EFI. Try again. If it not worked, This issue is happening may be because of File Vault Support on the EFI. If replacing your windows folder worked? let me know!. Between you did great job about detailing your Comment. High five.. 👍

**Comment by bunnybavros** [comment] 2023-01-20 18:51
Unfortunately, Replacing the Windows EFI is not working. T T
Using old EFI actually worked for dual boot, test twice.

**Comment by bunnybavros** [comment] 2023-01-20 18:57
By the way, I just replace **"BOOT"** folder and **"OC"** folder when I tried to switch between old EFI and new EFI. haha
https://user-images.githubusercontent.com/67104562/213782435-cc04be2b-e19f-44f0-9603-284e7b32c305.png

**Comment by devboloji** [comment] 2023-01-21 14:52
@bunnybavros Means the problem is from File Vault may be! Next time i will try disabling File Vault. So it may work. Get ready to test next release brother!. The update will be released soon.

**Closed by devboloji** 2023-01-21 14:52 UTC

**Comment by bunnybavros** [comment] 2023-01-21 15:20
Thank you so much!
I'll keep you on updated right after the new release it out! 🔥
